# Generated by Django 5.1 on 2024-08-23 10:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', ckeditor.fields.RichTextField()),
                ('phone_number', models.CharField(max_length=255)),
                ('picture', models.ImageField(upload_to='image')),
            ],
        ),
    ]
